apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: external-secrets-operator
spec:
  project: platform-engineering
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.8.1
    helm:
      # values: |
      skipCrds: false
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-operator
  info:
    - name: 'external-secrets-operator-chart-values'
      value: 'https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets'
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
  revisionHistoryLimit: 10
