apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: external-secrets-operator
spec:
  project: platform-engineering
  sources:
    # repoURL: https://charts.external-secrets.io
    # chart: external-secrets
    # targetRevision: 0.8.1
    # helm:
    #   skipCrds: false

    - repoURL: https://charts.external-secrets.io
      targetRevision: 0.8.1
      chart: external-secrets
      helm:
        # Helm values files for overriding values in the helm chart
        valueFiles:
        - $values/argocd/apps/external-secrets-operator/argo-values.yaml
        skipCrds: false
      ##? When using a upstream chart with values from custom repo
    - repoURL: 'https://github.com/ishuar/platform-engineering'
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-operator
  info:
    - name: 'external-secrets-operator-chart-values'
      value: 'https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets'
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - PrunePropagationPolicy=foreground
  revisionHistoryLimit: 10
ignoreDifferences:
  - group: apps
    kind: Application
    namespace: argocd
    name: external-secrets-operator
    jsonPointers:
    - /spec/source/helm