---
## Workload Identity ref: https://github.com/external-secrets/external-secrets/blob/9be0f87794ca2d8986805662035fc6caeec60ba3/docs/snippets/azkv-workload-identity.yaml
## ref: https://external-secrets.io/v0.4.4/provider-azure-key-vault/
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-cluster-secret-store
  namespace: external-secrets-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://kv-platform-secrets-01.vault.azure.net/"
      serviceAccountRef:
        name: sa-external-secrets-operator
