apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: azure-secret-store
  namespace: external-secrets-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    # provider type: azure keyvault
    azurekv:
      # azure tenant ID, see: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant
      tenantId: "9c1de352-64a4-4509-b3fc-4ef2df8db9b8"
      # URL of your vault instance, see: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates
      vaultUrl: "https://kv-platform-secrets-01.vault.azure.net/"
      authType: ServicePrincipal
      authSecretRef:
        # points to the secret that contains
        # the azure service principal credentials
        #? Secret was created manually using: kubectl create secret generic azure-key-vault-backend --from-literal=clientId=XYZ --from-literal clientSecret=ABC -n external-secrets-operator
        clientId:
          name: azure-key-vault-backend
          key: clientId
          namespace: external-secrets-operator
        clientSecret:
          name: azure-key-vault-backend
          key: clientSecret
          namespace: external-secrets-operator

