apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: my-crossplane-rg
spec:
  forProvider:
    location: "West Europe"
  ## the spec.providerConfigRef.name must match the ProviderConfig metadata.name value.
  providerConfigRef:
    name: crossplane-azure
