##? ref : https://external-secrets.io/v0.4.4/guides-templating/#templatefrom
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crossplane-config-tpl
  namespace: crossplane
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  azure.json: |-
    {
      "clientId": "{{ .crossplaneclientid }}",
      "clientSecret": "{{ .crossplaneclientsecret }}",
      "subscriptionId": "be01e8d6-72e0-4c3d-b7ae-afd4aa1224e6",
      "tenantId": "9c1de352-64a4-4509-b3fc-4ef2df8db9b8",
      "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
      "resourceManagerEndpointUrl": "https://management.azure.com/",
      "activeDirectoryGraphResourceId": "https://graph.windows.net/",
      "sqlManagementEndpointUrl": "https://management.core.windows.net:8443/",
      "galleryEndpointUrl": "https://gallery.azure.com/",
      "managementEndpointUrl": "https://management.core.windows.net/"
    }
