##? ref : https://external-secrets.io/v0.4.4/guides-templating/#templatefrom
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crossplane-config-tpl
  namespace: crossplane
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  azure.json: |-
    {
      "clientId": "{{ .crossplaneclientid }}",
      "clientSecret": "{{ .crossplaneclientsecret }}",
      "subscriptionId": "{{ .subscriptionid }}",
      "tenantId": "{{ .tenantid }}",
      "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
      "resourceManagerEndpointUrl": "https://management.azure.com/",
      "activeDirectoryGraphResourceId": "https://graph.windows.net/",
      "sqlManagementEndpointUrl": "https://management.core.windows.net:8443/",
      "galleryEndpointUrl": "https://gallery.azure.com/",
      "managementEndpointUrl": "https://management.core.windows.net/"
    }
