##? ref: https://external-secrets.io/v0.4.4/provider-azure-key-vault/
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: crossplane-external-secret
  namespace: crossplane
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-cluster-secret-store
  target:
    name: crossplane-azure-secret
    template:
      engineVersion: v2
      templateFrom:
      - configMap:
          # name of the configmap to pull in
          name: crossplane-config-tpl
          # here you define the keys that should be used as template
          items:
          - key: azure.json
  data:
  - secretKey: crossplaneclientid
    remoteRef:
      key: spn-platform-engineering-owner-crossplane-clientid # from terraform resource platform-engineering/terraform/terraform-kubernetes-resources/key-vault-and-secrets.tf
  - secretKey: crossplaneclientsecret
    remoteRef:
      key: spn-platform-engineering-owner-crossplane-clientsecret # from terraform resource platform-engineering/terraform/terraform-kubernetes-resources/key-vault-and-secrets.tf
  - secretKey: subscriptionid
    remoteRef:
      key: subscriptionid # from terraform resource platform-engineering/terraform/terraform-kubernetes-resources/key-vault-and-secrets.tf
  - secretKey: tenantid
    remoteRef:
      key: tenantid # from terraform resource platform-engineering/terraform/terraform-kubernetes-resources/key-vault-and-secrets.tf