# ---
# allowVolumeExpansion: true
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   labels:
#     addonmanager.kubernetes.io/mode: EnsureExists
#     kubernetes.io/cluster-service: "true"
#   annotations:
#     argocd.argoproj.io/sync-wave: "0"
#   name: managed-csi-retain
# parameters:
#   skuname: StandardSSD_LRS
# provisioner: disk.csi.azure.com
# reclaimPolicy: Retain
# volumeBindingMode: WaitForFirstConsumer
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: crossplan-package-cache
#   namespace: crossplane
#   annotations:
#     argocd.argoproj.io/sync-wave: "5"
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 5Gi
#   storageClassName: managed-csi-retain
