apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespaces.yaml
  - ./apps/external-secrets-operator/application.yaml
  - ./apps/external-secrets-operator/secretstore.yaml
  - ./apps/external-dns/application.yaml
  - ./apps/external-dns/configmap-template.yaml
  - ./apps/external-dns/externalsecret.yaml
  - ./apps/cert-manager/application.yaml
  - ./apps/cert-manager/clusterissuer.yaml
  - ./apps/cert-manager/externalsecret.yaml
  - ./apps/crossplane/application.yaml
  - ./apps/crossplane/configmap-template.yaml
  - ./apps/crossplane/externalsecret.yaml
  - ./apps/crossplane/providerconfig.yaml
  # - ./apps/crossplane/pvc.yaml
  - ./apps/azure-infrastructure-crossplane/application.yaml
