apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./apps/external-secrets-operator/application.yaml
  - ./apps/external-secrets-operator/secretstore.yaml
  # - ./apps/external-dns/application.yaml
