#? values source : https://artifacthub.io/packages/helm/bitnami/external-dns
provider: azure
azure:
  secretName: external-dns-secret-cluster
rbac:
  clusterRole: true
  create: true
sources:
  - ingress
domainFilters:
  - service.learndevops.in
