##? ref: https://external-secrets.io/v0.4.4/provider-azure-key-vault/
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-dns-external-secret
  namespace: external-secrets-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-secret-store
    namespace: external-secrets-operator
  target:
    name: external-dns-secret-cluster
    namespace: external-dns
    template:
      engineVersion: v2
      templateFrom:
      - configMap:
          # name of the configmap to pull in
          name: external-dns-config-tpl
          # here you define the keys that should be used as template
          items:
          - key: config.yaml
  data:
  - secretKey: externaldnsclientid
    remoteRef:
      key: externaldnsclientid
  - secretKey: externaldnsclientsecret
    remoteRef:
      key: externaldnsclientsecret
