##? ref: https://external-secrets.io/v0.4.4/provider-azure-key-vault/
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: external-dns-external-secret
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-cluster-secret-store
  target:
    name: external-dns-secret-cluster
    template:
      engineVersion: v2
      templateFrom:
      - configMap:
          # name of the configmap to pull in
          name: external-dns-config-tpl
          # here you define the keys that should be used as template
          items:
          - key: azure.json
  data:
  - secretKey: externaldnsclientid
    remoteRef:
      key: spn-platform-engineering-dns-admin-clientid
  - secretKey: externaldnsclientsecret
    remoteRef:
      key: spn-platform-engineering-dns-admin-clientsecret
