##? ref: https://cert-manager.io/v1.0-docs/configuration/acme/dns01/azuredns/
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: ishansharma887@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-staging
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: nginx
    - dns01:
        azureDNS:
          clientID: d504f8c9-4fb9-4b0a-94b1-a27b2740711c
          clientSecretSecretRef:
            key: externaldnsclientsecret # using the same from externalDNS for DNS challenges.
            name: cert-manager-dns01-azure-secret
          environment: AzurePublicCloud
          hostedZoneName: worldofcontainers.tk ## Use you domain
          resourceGroupName: rg-aks-mgmt-platform-engineering ## Resource Group where DNS zone is created
          subscriptionID: be01e8d6-72e0-4c3d-b7ae-afd4aa1224e6
          tenantID: 9c1de352-64a4-4509-b3fc-4ef2df8db9b8
