##? ref: https://external-secrets.io/v0.4.4/provider-azure-key-vault/
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: cert-manager-external-secret
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-cluster-secret-store
  target:
    name: cert-manager-dns01-azure-secret
  data:
  - secretKey: spn-platform-engineering-dns-admin-clientsecret ## required in clusterissuer.yaml
    remoteRef:
      key: spn-platform-engineering-dns-admin-clientsecret
